site_name: Loki Docs
site_author: lokeshreddy
theme:
  name: material
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Page tree
nav:
  - Home: index.md

  - Linux:
      - Useful shortcuts: linux/shortcuts.md
      - Basic Commands: linux/commands.md
      
  - Git:
      - Intro: git/basic.md

  - Docker:
      - Cheet Sheet: docker/docker-sheet.md
      - Docker Compose: docker/docker-compose.md
      - Utilities:
          - docker/utilities/index.md
          - Handbrake Video Compress: docker/utilities/handbrake.md

  - MYSQL:
      - Commands: mysql/commands.md
      - MySQL in Jupyter Notebook : mysql/mysql-in-jupyter-notebook.md

  - Remote Jobs:
      - Links: remote-jobs/index.md

# plugins:
#   - blogging:
#       dirs: # The directories to be included
#         - blog

#     - search
#     - mermaid2:
#         arguments:
#           theme: 'dark'

# extra_javascript:
#     - https://unpkg.com/mermaid/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
